In [6]:
import pandas as pd
import matplotlib as plt
import numpy as np
import sklearn
import pandas as pd

In [9]:
arr = np.loadtxt('chocolate_rating.csv',  delimiter=',')
arr


array([[1.000e+00, 2.016e+03, 6.300e-01, 3.750e+00],
       [2.000e+00, 2.015e+03, 7.000e-01, 2.750e+00],
       [3.000e+00, 2.015e+03, 7.000e-01, 3.000e+00],
       ...,
       [1.793e+03, 2.011e+03, 6.500e-01, 3.500e+00],
       [1.794e+03, 2.011e+03, 6.200e-01, 3.250e+00],
       [1.795e+03, 2.010e+03, 6.500e-01, 3.000e+00]])

In [12]:
avg = np.mean(arr[:,3])
avg

3.185933147632312

In [20]:
arr_3 = arr[:,3]
arr_3

array([3.75, 2.75, 3.  , ..., 3.5 , 3.25, 3.  ])

In [21]:
high_level = 

array([False, False, False, ..., False, False, False])